registries:
  - host: ghcr.io
    username: "{{ .Env.GHCR_USERNAME }}"
    password: "{{ .Env.GHCR_TOKEN }}"

services:
  dashboard:
    description: "factonet Lead Dashboard"
    image: ghcr.io/mtmstudios/facto-lead-flow:latest
    ports:
      - "80"
